### PR TITLE
Do you allow PRs? - Adding condition when .git is in /wp-content

### PR DESCRIPTION
**Pull request by davidvexel**
For our projects, we track `/wp-content`. By adding this condition my project is working fine. Thank you for your work btw, it is a wonderful idea.

### CODE REVIEW

**Comment by swaincreates** [comment]
Hey, thanks for submitting a PR! I don't really keep up with this anymore. Would you like to take over the plugin? Not sure how to do that in WP-land. Also, feel free to fork this and put your own plugin in the WP repositories. All that being said, I would gladly merge here - just not sure when i'll be able to get it uploaded to WP repository.

**Comment by swaincreates** [comment]
Merged, but feel free to respond on this PR to discuss my previous comment

**Comment by davidvexel** [comment]
Hey there, I was just about to write something like this when I found your plugin. I'm not very familiar with the WP repositories but this could be the perfect moment to start, so yes, I would love to take it over, thank you.

I already forked this plugin, I'll dig a bit into the docs to see how to submit this again.

Regards.

**Comment by swaincreates** [comment]
Great, let me know if there's anything I can do to help!

**Pull request merged**
